// DZX Filter Main JavaScript
// Generated by DZX Filter Build System

/**
 * Fetch the latest tag from GitHub and update the version display
 */
async function fetchLatestTag() {
    try {
        const response = await fetch('https://api.github.com/repos/darkzerox/Darkxee-Poe2Filter/tags');
        if (!response.ok) throw new Error('Network response was not ok');
        const tags = await response.json();
        const latestTag = tags[0]?.name || 'v1.0.16';
        
        // Update version display
        const versionElement = document.getElementById('repo-version');
        if (versionElement) {
            versionElement.innerText = latestTag;
        }
        
        // Update page title
        document.title = `DZX Filter for POE2 - ${latestTag} | Path of Exile 2 Item Filter`;
    } catch (error) {
        console.error('Error fetching latest tag:', error);
        // Keep default version if fetch fails
    }
}

/**
 * Initialize the application
 */
function initApp() {
    console.log('DZX Filter Preview initialized');
    fetchLatestTag();
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', initApp);