name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Release info: ${{ toJSON(github.event.release) }}"
          
      - name: Get release information
        id: release_info
        run: |
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
          echo "url=${{ github.event.release.html_url }}" >> $GITHUB_OUTPUT
          echo "body=${{ github.event.release.body }}" >> $GITHUB_OUTPUT
          
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "🚀 ${{ steps.release_info.outputs.name }}"
          description: "${{ steps.release_info.outputs.body }}"
          url: "${{ steps.release_info.outputs.url }}"
          color: 5814783
          username: "DZX Filter POE2 Release Bot"
          avatar_url: "https://raw.githubusercontent.com/${{ github.repository }}/master/dzx_filter/images/dzx-poe2-filter-logo.png"
          fields: |
            [
              { "name": "เวอร์ชัน", "value": "${{ steps.release_info.outputs.version }}", "inline": true },
              { "name": "ผู้ปล่อย", "value": "${{ github.actor }}", "inline": true }
            ]
          footer: "DZX Filter POE2 | ปล่อยเมื่อ ${{ github.event.release.published_at }}"
