name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build installer
      run: python build_installer.py
    
    - name: Create release package
      run: |
        mkdir -p release
        cd dist/POE2FilterInstaller_Package
        zip -r ../../release/POE2FilterInstaller-${{ github.ref_name }}.zip .
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: POE2 Filter Installer ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/POE2FilterInstaller-${{ github.ref_name }}.zip
        asset_name: POE2FilterInstaller-${{ github.ref_name }}.zip
        asset_content_type: application/zip
