name: Run build file for dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write  # Ensure the workflow has permission to push changes

jobs:
  buildFilter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
     
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pull latest changes
        run: git pull origin develop  # Pull from master branch

      - name: execute py script
        run: |
          python script/run_script.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [ -n "$(git status --porcelain)" ]; then
          git commit -m "build file completed"
          git push
            else
          echo "No changes to commit"
            fi